#!/usr/bin/env python3
"""Build the web reference and a one-page A3 PDF from the curated binding catalog."""
import json
from html import escape
from pathlib import Path

from pypdf import PdfReader
from reportlab.lib import colors
from reportlab.lib.pagesizes import A3, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph

ROOT = Path(__file__).resolve().parents[1]
SECTIONS = json.loads((ROOT / "docs/keybindings.json").read_text())
PDF = ROOT / "docs/assets/neovim-a3-cheat-sheet.pdf"
WIDTH, HEIGHT = landscape(A3)
MARGIN, GAP = 28, 18
COL_WIDTH = (WIDTH - 2 * MARGIN - 3 * GAP) / 4
INK = colors.HexColor("#18313e")
TEAL = colors.HexColor("#126d73")
MUTED = colors.HexColor("#506373")


def paragraph(text, x, top, width, font="Helvetica", size=9.5, color=INK, leading=None):
    style = ParagraphStyle("text", fontName=font, fontSize=size,
                           leading=leading or size * 1.12, textColor=color)
    block = Paragraph(escape(text), style)
    _, height = block.wrap(width, HEIGHT)
    if top - height < 32:
        raise ValueError(f"Cheat sheet overflow near: {text!r}")
    block.drawOn(c, x, top - height)
    return height


def md_cell(text):
    return text.replace("|", "\\|")


lines = ["# Keybinding reference", "",
         "<!-- Generated by scripts/build-cheat-sheet.py from keybindings.json. -->", "",
         "[Download the A3 landscape PDF](assets/neovim-a3-cheat-sheet.pdf).", "",
         "Leader is **comma**. Keys are in **Normal mode** unless marked otherwise. "
         "Type comma sequences one key at a time; hold Control for `Ctrl-` keys. "
         "`Enter` is `<CR>`, `Shift-Tab` is `<S-Tab>`, and uppercase letters are significant.", "",
         "**Full** means mac_home, mac_office, ubuntu or rhel8_vm. "
         "**Minimal** means euhpc3 or minimal. **Work Linux** means ubuntu, rhel8_vm or euhpc3. "
         "LSP and Git buffer maps require their clients/plugins to attach. "
         "Plugin defaults and native commands are explicitly labeled.", ""]
for section in SECTIONS:
    lines += [f"## {section['title']}", "", f"**{section['scope']}**", "",
              "| Keys / command | Action |", "| --- | --- |"]
    for row in section["rows"]:
        lines.append(f"| `{md_cell(row['keys'])}` | {md_cell(row['action'])} |")
    if section["note"]:
        lines += ["", section["note"]]
    lines += ["", f"Source: `{section['source']}`.", ""]
(ROOT / "docs/keybindings.md").write_text("\n".join(lines))

PDF.parent.mkdir(parents=True, exist_ok=True)
c = canvas.Canvas(str(PDF), pagesize=(WIDTH, HEIGHT), invariant=1)
c.setTitle("Neovim field guide - A3 keybinding cheat sheet")
c.setAuthor("Neovim configuration")
c.setFillColor(INK)
c.rect(0, HEIGHT - 85, WIDTH, 85, fill=1, stroke=0)
paragraph("NEOVIM / FIELD GUIDE", MARGIN, HEIGHT - 17, 800,
          font="Helvetica-Bold", size=24, color=colors.white)
paragraph("Leader = comma   |   Normal mode unless marked   |   A3 landscape - print at 100%",
          MARGIN, HEIGHT - 50, WIDTH - 2 * MARGIN, size=10, color=colors.HexColor("#d8eeee"))
paragraph("FULL: Mac / Ubuntu / RHEL8    MINIMAL: EUHPC3 / minimal    WORK LINUX: Ubuntu / RHEL8 / EUHPC3",
          MARGIN, HEIGHT - 66, WIDTH - 2 * MARGIN, size=8.5, color=colors.HexColor("#d8eeee"))
heights = []
for col in range(4):
    x, top = MARGIN + col * (COL_WIDTH + GAP), HEIGHT - 99
    for section in [s for s in SECTIONS if s["column"] == col]:
        c.setFillColor(TEAL)
        c.roundRect(x, top - 21, COL_WIDTH, 21, 3, fill=1, stroke=0)
        paragraph(section["title"].upper(), x + 7, top - 5, COL_WIDTH - 14,
                  font="Helvetica-Bold", size=10, color=colors.white)
        top -= 26
        top -= paragraph(section["scope"], x + 1, top, COL_WIDTH - 2, size=7.7, color=MUTED) + 5
        for i, row in enumerate(section["rows"]):
            # Long command names get their own line so type remains readable.
            stacked = len(row["keys"]) > 23
            if stacked:
                kh = paragraph(row["keys"], x + 3, top, COL_WIDTH - 6,
                               font="Courier-Bold", size=8.6)
                ah = paragraph(row["action"], x + 9, top - kh - 1, COL_WIDTH - 12, size=9)
                height = kh + ah + 3
            else:
                kw = 121
                kh = paragraph(row["keys"], x + 3, top, kw - 7, font="Courier-Bold", size=8.6)
                ah = paragraph(row["action"], x + kw, top, COL_WIDTH - kw - 3, size=9)
                height = max(kh, ah) + 3
            top -= height
            c.setStrokeColor(colors.HexColor("#e3e9eb"))
            c.setLineWidth(.35)
            c.line(x, top + 2, x + COL_WIDTH, top + 2)
        if section["note"]:
            top -= 2
            top -= paragraph(section["note"], x + 3, top, COL_WIDTH - 6, size=7.8, color=MUTED) + 3
        top -= 9
    heights.append(round(top, 1))
    if top < 32:
        raise ValueError(f"Column {col + 1} overflows: {top}")
c.setStrokeColor(TEAL)
c.line(MARGIN, 28, WIDTH - MARGIN, 28)
c.setFont("Helvetica", 8)
c.setFillColor(MUTED)
c.drawString(MARGIN, 16, "Shared master configuration  |  Full explanations in the MkDocs guide  |  :verbose nmap {keys} shows the effective mapping")
c.save()
reader = PdfReader(PDF)
assert len(reader.pages) == 1, "Expected one page"
page = reader.pages[0]
assert abs(float(page.mediabox.width) - WIDTH) < .1
assert abs(float(page.mediabox.height) - HEIGHT) < .1
text = page.extract_text()
for section in SECTIONS:
    assert section["title"].upper() in text
print(f"Built {PDF.relative_to(ROOT)}; {sum(len(s['rows']) for s in SECTIONS)} entries; column bottoms {heights}")
